### ISSUE TITLE
Intended cable for facedancer capability

### ISSUE THREAD

**Issue by chadrockey** [greatfet-hardware/azalea#1]
I just received my unit today and noticed that it was micro usb and not USB type c (I didn't loo closely) for both connectors.

I was planning on using my GreatFet one as a Facedancer interface, but the included cable is a typical micro usb cable.

Longer term, it would be nice to use type-c for at least the target connection since those cables are reversible (host/target, not cable orientation) by design.

Medium term, it would be nice to include the intended micro-usb to target (female A?) cable.  I think we all have enough typical micro-usb around.

Short term, what cable is intended for my use of the greatfet one as a fancedancer?  A typical USB OTG Host cable?  Any suggested links or known good host cables?

**Comment by mossmann** [comment]
The most common cabling for Facedancer is to use a micro cable (such as the one that ships with GreatFET One) to connect USB0 to your host computer and another micro cable to connect USB1 to a target computer.  We don't include a second cable because, as you pointed out, most folks have plenty already, and because we expect that some GreatFET users will never use USB1.

If you want to connect USB1 to a target device instead of a target host, you can use an OTG cable or adapter. This is a less common configuration because people typically use ports on their host computer (e.g. with PyUSB) for experimenting with target USB devices.

If there is a successor to Azalea it will probably have two Type-C connectors.
